name: StockMarket
main: org.xjcraft.trade.StockMarket
version: 1.2
author: Ree
description: This plugin is used to simulated a stock market
website: http://www.xjcraft.org/
database: true

commands:
    trade:
        description: Contains all commands in [StockMarket],can be shorted as /tr.
        usage: use /<command> help to show all commands avaliable in plugin
        permission: trade.command
        permission-message: You don't have <permission>
    tr:
            description: Contains all commands in [StockMarket].
            usage: use /<command> h to show all commands avaliable in plugin
            permission: trade.command
            permission-message: You don't have <permission>

permissions:
    trade.command:
        description: Allow user to use trade command
        default: true
    trade.enable:
        description: Allow user to use trade plugin
        default: true
    trade.create:
        description: Allow user to create shop
        default: op


