name: StockMarket
#main: org.xjcraft.blockFML.OnlineLoginPluginDemo
main: org.xjcraft.trade.StockMarket
api-version: '1.18'
version: ${project.version}
author: Ree
description: This plugin is used to simulated a stock market
website: http://www.xjcraft.org/
depend: [MultiCurrency]

commands:
    trade:
        description: Contains all commands in [StockMarket],can be shorted as /tr.
        usage: use /<command> help to show all commands avaliable in plugin
        permission: trade.command
        permission-message: You don't have <permission>
    tr:
            description: Contains all commands in [StockMarket].
            usage: use /<command> h to show all commands avaliable in plugin
            permission: trade.command
            permission-message: You don't have <permission>

permissions:
    trade.command:
        description: Allow user to use trade command
        default: op
    trade.enable:
        description: Allow user to use trade plugin
        default: op
    trade.create:
        description: Allow user to create shop
        default: op


